<Project>

  <!-- Import our shared user configuration file -->
  <Import
    Project="$(SolutionRoot)Config.Build.user.props"
    Condition="Exists('$(SolutionRoot)Config.Build.user.props')"
  />

  <!-- Primary configuration for the project -->
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <UseArtifactsOutput>true</UseArtifactsOutput>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>embedded</DebugType>
	  
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=./</PathMap>
  </PropertyGroup>

  <!-- Custom props -->
  <PropertyGroup>
    <SolutionRoot>$(MSBuildThisFileDirectory)</SolutionRoot>
    <PathBeforeSteam Condition="'$([MSBuild]::IsOSUnixLike())' == 'true'">$(HOME)/.local/share/</PathBeforeSteam>
    <PathBeforeSteam Condition="'$([MSBuild]::IsOSUnixLike())' != 'true'">$(MSBuildProgramFiles32)/</PathBeforeSteam>
	<GameLoc Condition="$(GameLoc) == ''">C:\Program Files (x86)\Steam\steamapps\common\Lethal Company</GameLoc>
    <PluginsDir Condition="$(PluginsDir) == ''">C:\Program Files (x86)\Steam\steamapps\common\Lethal Company/BepInEx/plugins/</PluginsDir>
    <ManagedDir>$(GameLoc)/Lethal Company_Data/Managed/</ManagedDir>
  </PropertyGroup>

</Project>
